## **Getting started with Numpy**

In [1]:
#I hope all of you know fundamentals of programming and basics of python

import numpy as np

## **Assess Arrays**

In [2]:
arr = np.array([(1,2,3), (4,5,6)])

print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
print(arr.size)

6


In [4]:
print(arr.shape)

(2, 3)


In [5]:
print(arr.ndim)

2


In [6]:
print(arr.dtype.name)

int64


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
print(arr.itemsize)

8


## **Creating Arrays**

In [9]:
arr0 = np.array([1.1,2.2,3.3,4.4], dtype=complex)
print(arr0)

[1.1+0.j 2.2+0.j 3.3+0.j 4.4+0.j]


In [10]:
arr1 = np.arange(24)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [11]:
arr2 = np.arange(12, 24)
print(arr2)

[12 13 14 15 16 17 18 19 20 21 22 23]


In [12]:
arr3 = np.arange(12, 24, 2)
print(arr3)

[12 14 16 18 20 22]


In [13]:
arr4 = arr1.reshape(2, 3, 4)
print(arr4)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [14]:
arr5 = np.zeros((6,7), dtype=np.int64)
print(arr5)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


## **Basic Operations**

In [15]:
x = np.arange(12,24)
y = np.arange(0,24, 2)

print(x)
print("\n"*2)
print(y)

[12 13 14 15 16 17 18 19 20 21 22 23]



[ 0  2  4  6  8 10 12 14 16 18 20 22]


In [16]:
print(x-y)
print("\n"*2)
print(x*y)

[12 11 10  9  8  7  6  5  4  3  2  1]



[  0  26  56  90 128 170 216 266 320 378 440 506]


In [17]:
print(x+10)
print("\n"*2)
print(y>10)
print("\n"*2)
print(y**3)

[22 23 24 25 26 27 28 29 30 31 32 33]



[False False False False False False  True  True  True  True  True  True]



[    0     8    64   216   512  1000  1728  2744  4096  5832  8000 10648]


In [18]:
print(x.max())
print("\n"*2)
print(x.min())
print("\n"*2)
print(x.sum())

23



12



210


In [19]:
print(np.sqrt(x))

[3.46410162 3.60555128 3.74165739 3.87298335 4.         4.12310563
 4.24264069 4.35889894 4.47213595 4.58257569 4.69041576 4.79583152]


In [20]:
temp1 = np.arange(24).reshape(4,6)
temp2 = np.arange(24,48).reshape(6,4)

print(temp1)
print(temp2)
print(""*3)
# print(temp.sum(axis=1))
# print(temp.max(axis=0))
# print(temp.min(axis=1))

# print(temp1*temp2)
print(temp1@temp2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]]

[[ 580  595  610  625]
 [1804 1855 1906 1957]
 [3028 3115 3202 3289]
 [4252 4375 4498 4621]]


In [21]:
temp3 = np.random.default_rng(3)

temp4 = temp3.random((6,4))

print(temp4*8)

[[0.68519334 1.89448405 6.41019572 4.65729629]
 [0.75302914 3.46501552 3.83241039 1.27791132]
 [5.87661721 0.90937616 3.12982552 4.13392146]
 [3.44502416 4.69438857 5.9027023  7.65013804]
 [2.27360931 5.18837766 5.56972797 2.34176599]
 [0.01192067 7.7876822  2.38720978 2.51188802]]


# **Thank you.**